config/routes.rb
Rails.application.routes.draw do
  resources :accounts

  root 'welcome#index'
  devise_for :users
  resources :users do
    resource :account
  end
  

  

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  degree_before :integer
#  degree_after  :integer
#  birth_name    :string
#  birth_date    :string
#  gender        :integer
#  birth_place   :string
#  birth_number  :string
#  nationality   :string
#  family_status :integer
#  bank_acc      :string
#  insurance     :string
#  occupation    :string
#  terms         :boolean
#  status        :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Account < ActiveRecord::Base
  
  belongs_to :user
  
  # Validations
  validates_presence_of :user_id, :on => :update
  validates_presence_of :birth_name, :on => :update
  #validates_presence_of :birth_date, :on => :update
  #validates_presence_of :gender, :on => :update
  #validates_presence_of :birth_place, :on => :update
  #validates_presence_of :birth_number, :on => :update
  #validates_presence_of :nationality, :on => :update
  #validates_presence_of :family_status, :on => :update
  #validates_presence_of :bank_acc, :on => :update
  #validates_presence_of :insurance, :on => :update
  #validates_presence_of :occupation, :on => :update
  #validates_presence_of :terms, :on => :update
  
  
  #attr_accessor :user_id
  
  # enums
  enum degree_before: [:ing, :phdr]
  enum degree_after: [:csc, :dis]
  enum gender: [:man, :woman]
  enum family_status: [:single, :married, :widow]
  
  #  enum family_status: #[:banned, :inactive,:active]
  #  enum occupation: #[:man, :woman]
  enum status: [:ended, :started, :completed]
  
  # set default entries
  after_initialize :set_default_values, :if => :new_record?
  
  def set_default_values
    self.status ||= :started
    self.terms  ||= false
  end
  
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  first_name             :string
#  last_name              :string
#  role                   :integer
#  status                 :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  
  
  has_one :account, dependent: :destroy
  accepts_nested_attributes_for :account
  
         
  # Devise validates email and password automatically
  validates_presence_of :first_name
  validates_presence_of :last_name
  
  enum role: [:pending, :user, :manager, :admin]
  enum status: [:banned, :inactive, :active]
  
  # sets default settings and build account for user
  after_initialize :set_default_role_and_status, :if => :new_record?
  after_initialize :build_new_account, :if => :new_record?
  
  def set_default_role_and_status
    self.role ||= :pending
    self.status ||= :inactive
  end
  
  def build_new_account
    self.account ||= self.build_account()
  end

  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  # TODO: ONLY FORM ADMINS !!
  
  before_action :authenticate_user!
  before_action :set_account, except: [:index, :new, :create]
  
  def index
    @accounts = Account.all
  end

  def show
    @user = @account.user
  end

  def new
    @account = Account.new
    @account.addresses.new
  end


  def edit
    #@account = Account.find(params[:id])
    @user = @account.user
    #Person.create(person_params)
  end
  
  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Účet byl upraven.' 
    else
      render :edit
    end
  end
  
  private
    
    def full_name
		  self.full_name = [first_name, last_name].join(' ')
	  end
	  
    def set_account
      #@user =    #current_user  #User.find(params[:id])
      #@account = @user.account
      @account = Account.find(params[:id])
      
      #@account = Account.find(params[:id])
      #@user = @account.user
      #@account = Account.where(params[:user_id] = current_user.id)
    end
  
    def account_params
      params.require(:account).permit(:birth_name, :birth_place, :birth_number)
      
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def create
    super
  end
  
  protected
	  
    def after_sign_up_path_for(resource)
      #after_register_path(:add_name)
    end
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :remember_me, :first_name, :last_name])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :password_confirmation,
                                                                :confiramtion_token, :confirmed_at, :confirmation_sent_at, :role, :status,
                                                                account_attributes: [:birth_name]])
    end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authenticate_user!
  #before_action :set_users_account, only: [:index]
  
  
  #after_action :verify_authorized
  
  def index
    @users = User.all
    #authorize User
  end
  
  def show
    @account = @user.account
    #authorize @user
  end
  
  def edit
    #authorize current_user
  end
  
  def update
    #authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "Uživatel aktualizován."
    else
      redirect_to users_path, :alert => "Nebylo možné uživatele aktualizovat."
    end
  end
  
  def destroy
    user = User.find(params[:id])
    #authorize user
    user.destroy
    redirect_to users_path, :notice => "Uživatel byl smazán."
  end
  
  private
  
    def set_user
      @user = User.find(params[:id])
    end
    

    def secure_params
      params.require(:user).permit(:first_name, :last_name, :email, :role, :status,
                                  account_attributes: [:birth_name])
                                  
                                  # add account nested columns)
    end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/_form.html.erb
# TODO add simple_form

<%= form_for [@user, @account] do |f| %>

    <div class="form-group">
        <%= f.text_field%>
    </div>

<% end %>

app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

app/views/accounts/edit.html.erb
<h1>Upravujete účet : <%= @account.user.first_name + ' ' + @account.user.last_name %></h1>
<br>
<hr>
<br>
<h3>Právě prohlíží :</h3>
<p>current_user.id <%= current_user.id %></p>
<p>Role : <%= current_user.role %></p>
<p>Jméno : <%= current_user.first_name + ' ' + current_user.last_name %></p>

<%= simple_form_for @account, html: { multipart: true, class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f| %>
    <div class="col-sm-offset-3 col-sm-9"><%= f.error_notification %></div>
  <div class="form-inputs">
    
    
    
    <%= f.input :birth_name, label: 'Rodné příjmení' %>
    <!--TODO: gender-->
    <%= f.input :birth_place, label: 'Místo narození' %>
    <%= f.input :birth_number, label: 'Rodné číslo' %>
  </div>
    
  <div class="form-group"> 
    <div class='col-sm-offset-3 col-sm-9'>
      <%= f.button :submit, class: 'btn-success' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  accounts_path, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/accounts/index.html.erb
<div class="container col-md-12">
  
  
  
  <h2>Účty uživetelů</h2>
  <br>
  <p>Přehled všech účtů v systému :</p>
  <br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Jméno majitele</th>
        <th>Rodné příjmení</th>  
        <th>Status</th>
        <th>Akce</th>
      </tr>
    </thead>
    <tbody>
      <% for account in @accounts %>
        <tr>
          <td><%= account.user.first_name + ' ' + account.user.last_name %></td>
          <td><%= account.birth_name %></td>
          <td><%= t(account.status) %></td>
          
          <td>
              
              <%= link_to edit_account_path(account), :class => "table-link" do %>
						  	<span class="fa-stack">
						  		<i class="fa fa-square fa-stack-2x"></i>
						  		<i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
						  	</span>
						  <% end %>
						  
						  <%= link_to account_path(account), :class => "table-link" do %>
						  	<span class="fa-stack">
						  		<i class="fa fa-square fa-stack-2x"></i>
						  		<i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
						  	</span>
						  <% end %>
						  		
            </td>
          </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/new.html.erb
<h1>Accounts#new</h1>
<p>Find me in app/views/accounts/new.html.erb</p>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>
<p>Jméno : <%= @user.first_name + ' ' + @user.last_name %></p>
<p>user_id <%= @user.account.user_id %></p>
<p>account_id <%= @user.account.id %></p>
<p>@user.id <%= @user.id %></p>
<br>
<hr>
<br>
<h3>Právě prohlíží :</h3>
<p>current_user.id <%= current_user.id %></p>
<p>Role : <%= current_user.role %></p>
<p>Jméno : <%= current_user.first_name + ' ' + current_user.last_name %></p>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
	<div class="container">
		<nav>
					<center><p>SmartBitsApp &copy; 2016</p></center>
		</nav>
	</div>	
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <div class="navbar-header">
        <span><%= link_to "LP", root_path, id: "logo" %></span>
        <span class="beta">Alpha</span>
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <nav class="navbar-collapse bs-navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Dashboard", "#" %></li>
            <li><%= link_to "Uživatelé", users_path %></li>
            <li><%= link_to "Účty", accounts_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Můj profil", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Odhlásit se", destroy_user_session_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li class="nav-link"><%= link_to "Přihlásit se", new_user_session_path %></li>
            <li class="nav-link"><%= link_to "Registrovat se", new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Semifinal" %></title>
    <%= viewport_meta_tag(:maximum_scale => "1.0") %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <body class="<%= controller_name %> <%= action_name%>">
      
      <%= render 'layouts/header' %>
      
      <div class="container-fluid">
        <div class="row">
          
          <div class="col-md-10 col-md-offset-1 ">
            <div class="flash"><%= bootstrap_flash %></div>
            
              <div class="row">
                <%= yield :sidebar %>
                <%= yield %>
              </div>
              
          </div>
          
        </div><!--/row-->
        
        <%= render 'layouts/footer' %>
  
      </div> <!-- /container -->
      
      
  </body>
</html>

app/views/users/index.html.erb
<div class="container col-md-12">
  
  
  
  <h2>Uživatelé</h2>
  <div><%= console %></div>
  <p>Přehled všech uživatelů v systému :</p>
  <br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Jméno</th>
        <th class="hidden-sm hidden-xs">Registrace</th>
        <th class="hidden-xs">Email</th>
        <!--<th class="hidden-sm hidden-xs">Potvrzeno</th>-->
        <th>Role</th>
        <th>Účet</th>
        <th>Status</th>
        <th class="hidden-xs">Přihlášen</th>
        <th>Links</th>
      </tr>
    </thead>
    <tbody>
      <% for user in @users %>
        <tr>
          <td><%= user.first_name + ' ' + user.last_name %></td>
          <td class="hidden-sm hidden-xs">před <%= time_ago_in_words(user.created_at) %></td>
          <td class="hidden-xs"><%= user.email %></td>
          <!-- TODO strftime is nil! -->
          <!--<td class="hidden-sm hidden-xs"><%#= Date.parse(user.confirmed_at).strftime("%d.%m v %l:%Mh") %></td>-->
          <td><%= t(user.role) %></td>
          <td><%= t(user.account.status) %></td>
          <td><%= t(user.status) %></td>
          <td class="hidden-xs"><%= user.sign_in_count %>x</td>
          <td>
              
              <%= link_to edit_user_path(user), :class => "table-link" do %>
						  	<span class="fa-stack">
						  		<i class="fa fa-square fa-stack-2x"></i>
						  		<i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
						  	</span>
						  <% end %>
						  
						  <%= link_to user_path(user), :class => "table-link" do %>
						  	<span class="fa-stack">
						  		<i class="fa fa-square fa-stack-2x"></i>
						  		<i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
						  	</span>
						  <% end %>
						  		
            </td>
          </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<h1>Users#show view</h1>

<h4>Účet patří :</h4>
<p>@user.id <%= @user.id %></p>
<p>Jméno : <%= @user.first_name + ' ' + @user.last_name %></p>
<p>user_id <%= @user.account.user_id %></p>
<p>account_id <%= @user.account.id %></p>
<p>rodné příjmení <%= @account.birth_name %></p>
<p>místo narození <%= @account.birth_place %></p>
<p>rodné číslo <%= @account.birth_number %></p>
<br>
<hr>
<br>
<h3>Právě prohlíží :</h3>
<p># <%= current_user.id %> : <%= current_user.role %> : <%= current_user.first_name + ' ' + current_user.last_name %></p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>